/**
 * This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.Embedded;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * @author Eugene
 */
@MappedSuperclass
public abstract
	class AbstractConstruction {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private
	    Long id;

    @Basic
    private
	    String Appointment;

    @Embedded
    private
	    Address address;

    @Embedded
    private
	    Building building;

    @Embedded
    private
	    Room room;

    public
	    Long getId () {
	return this.id;
    }

    public
	    void setId (Long id) {
	this.id = id;
    }

    public
	    String getAppointment () {
	return this.Appointment;
    }

    public
	    void setAppointment (String Appointment) {
	this.Appointment = Appointment;
    }

    public
	    Address getAddress () {
	return this.address;
    }

    public
	    void setAddress (Address address) {
	this.address = address;
    }

    public
	    Building getBuilding () {
	return this.building;
    }

    public
	    void setBuilding (Building building) {
	this.building = building;
    }

    public
	    Room getRoom () {
	return this.room;
    }

    public
	    void setRoom (Room room) {
	this.room = room;
    }

}
