/**
 * This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.ElementCollection;
import javax.persistence.Embeddable;

/**
 * @author Eugene
 */
@Embeddable
public
	class Address {

    @Basic
    private
	    String Country;

    @Basic
    private
	    String Region;

    @Basic
    private
	    String City;

    @Basic
    private
	    String Street;

    @ElementCollection
    private
	    List<String> GEO_coordinates;

    public
	    String getCountry () {
	return this.Country;
    }

    public
	    void setCountry (String Country) {
	this.Country = Country;
    }

    public
	    String getRegion () {
	return this.Region;
    }

    public
	    void setRegion (String Region) {
	this.Region = Region;
    }

    public
	    String getCity () {
	return this.City;
    }

    public
	    void setCity (String City) {
	this.City = City;
    }

    public
	    String getStreet () {
	return this.Street;
    }

    public
	    void setStreet (String Street) {
	this.Street = Street;
    }

    public
	    List<String> getGEO_coordinates () {
	return this.GEO_coordinates;
    }

    public
	    void setGEO_coordinates (List<String> GEO_coordinates) {
	this.GEO_coordinates = GEO_coordinates;
    }

}
