/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 @author Admin
 */
@MappedSuperclass
public abstract class Document
{

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String SureName;

    @Basic
    private String Name;

    @Basic
    private String MiddleName;

    @Basic
    private String number;

    @Basic
    private String birthday;

    @Basic
    private String sex;

    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public String getSureName()
    {
        return this.SureName;
    }

    public void setSureName(String SureName)
    {
        this.SureName = SureName;
    }

    public String getName()
    {
        return this.Name;
    }

    public void setName(String Name)
    {
        this.Name = Name;
    }

    public String getMiddleName()
    {
        return this.MiddleName;
    }

    public void setMiddleName(String MiddleName)
    {
        this.MiddleName = MiddleName;
    }

    public String getNumber()
    {
        return this.number;
    }

    public void setNumber(String number)
    {
        this.number = number;
    }

    public String getBirthday()
    {
        return this.birthday;
    }

    public void setBirthday(String birthday)
    {
        this.birthday = birthday;
    }

    public String getSex()
    {
        return this.sex;
    }

    public void setSex(String sex)
    {
        this.sex = sex;
    }

}
