/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import java.sql.Date;
import javax.persistence.Basic;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 @author Admin
 */
@MappedSuperclass
public abstract class Document
{

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String SureName;

    @Basic
    private String Name;

    @Basic
    private String MiddleName;

    @Basic
    private Integer Number;

    @Basic
    private Date Birthday;

    @Basic
    private String Sex;

    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public String getSureName()
    {
        return this.SureName;
    }

    public void setSureName(String SureName)
    {
        this.SureName = SureName;
    }

    public String getName()
    {
        return this.Name;
    }

    public void setName(String Name)
    {
        this.Name = Name;
    }

    public String getMiddleName()
    {
        return this.MiddleName;
    }

    public void setMiddleName(String MiddleName)
    {
        this.MiddleName = MiddleName;
    }

    public Integer getNumber()
    {
        return this.Number;
    }

    public void setNumber(Integer Number)
    {
        this.Number = Number;
    }

    public Date getBirthday()
    {
        return this.Birthday;
    }

    public void setBirthday(Date Birthday)
    {
        this.Birthday = Birthday;
    }

    public String getSex()
    {
        return this.Sex;
    }

    public void setSex(String Sex)
    {
        this.Sex = Sex;
    }

}
