/**
 * This file was generated by the Jeddict
 */ 

package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 * @author Admin
 */

@Entity
public class Education extends Document { 

    @Basic
    private String Education;

    @Basic
    private String Series;

    @Basic
    private String DateOfIssue;

    public String getEducation() {
        return this.Education;
    }

    public void setEducation(String Education) {
        this.Education = Education;
    }


    public String getSeries() {
        return this.Series;
    }

    public void setSeries(String Series) {
        this.Series = Series;
    }


    public String getDateOfIssue() {
        return this.DateOfIssue;
    }

    public void setDateOfIssue(String DateOfIssue) {
        this.DateOfIssue = DateOfIssue;
    }


}
