/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 @author Admin
 */
@Entity
public class Employee extends Man implements Serializable
{

    @Basic
    private String Position;

    @Basic
    private String u;

    @Basic
    private String attribute1;

    public String getPosition()
    {
        return this.Position;
    }

    public void setPosition(String Position)
    {
        this.Position = Position;
    }

    public String getU()
    {
        return this.u;
    }

    public void setU(String u)
    {
        this.u = u;
    }

    public String getAttribute1()
    {
        return this.attribute1;
    }

    public void setAttribute1(String attribute1)
    {
        this.attribute1 = attribute1;
    }

}
