/**
 * This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 * @author Eugene
 */
@Entity
public class Home extends AbstractConstruction
{

    @Basic
    private String TypeOfOwnership;

    @Basic
    private String RegisteredTo;

    public String getTypeOfOwnership()
    {
        return this.TypeOfOwnership;
    }

    public void setTypeOfOwnership(String TypeOfOwnership)
    {
        this.TypeOfOwnership = TypeOfOwnership;
    }

    public String getRegisteredTo()
    {
        return this.RegisteredTo;
    }

    public void setRegisteredTo(String RegisteredTo)
    {
        this.RegisteredTo = RegisteredTo;
    }

}
