/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 @author Vadim
 */
@Entity
public class Information_of_Works extends Reports
{

    @Basic
    private String Type_of_Work;

    @Basic
    private String Date_of_Registration;

    @Basic
    private String Theme;

    @Basic
    private String Date_of_Protection;

    @Basic
    private String Valuation;

    public String getType_of_Work()
    {
        return this.Type_of_Work;
    }

    public void setType_of_Work(String Type_of_Work)
    {
        this.Type_of_Work = Type_of_Work;
    }

    public String getDate_of_Registration()
    {
        return this.Date_of_Registration;
    }

    public void setDate_of_Registration(String Date_of_Registration)
    {
        this.Date_of_Registration = Date_of_Registration;
    }

    public String getTheme()
    {
        return this.Theme;
    }

    public void setTheme(String Theme)
    {
        this.Theme = Theme;
    }

    public String getDate_of_Protection()
    {
        return this.Date_of_Protection;
    }

    public void setDate_of_Protection(String Date_of_Protection)
    {
        this.Date_of_Protection = Date_of_Protection;
    }

    public String getValuation()
    {
        return this.Valuation;
    }

    public void setValuation(String Valuation)
    {
        this.Valuation = Valuation;
    }

}
