/**
 * This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 * @author Eugene
 */
@Entity
public
	class Institute extends AbstractConstruction {

    @Basic
    private
	    String NameOfInstitute;

    @Basic
    private
	    String IsFilial;

    @Basic
    private
	    String TotalStidents;

    public
	    String getNameOfInstitute () {
	return this.NameOfInstitute;
    }

    public
	    void setNameOfInstitute (String NameOfInstitute) {
	this.NameOfInstitute = NameOfInstitute;
    }

    public
	    String getIsFilial () {
	return this.IsFilial;
    }

    public
	    void setIsFilial (String IsFilial) {
	this.IsFilial = IsFilial;
    }

    public
	    String getTotalStidents () {
	return this.TotalStidents;
    }

    public
	    void setTotalStidents (String TotalStidents) {
	this.TotalStidents = TotalStidents;
    }

}
