/**
 * This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.MappedSuperclass;

/**
 * @author vaganovdv
 */
@MappedSuperclass
public abstract class Man
{

}
