/**
 * This file was generated by the Jeddict
 */ 

package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 * @author Admin
 */

@Entity
public class MilitaryID extends Document { 

    @Basic
    private String Series;

    public String getSeries() {
        return this.Series;
    }

    public void setSeries(String Series) {
        this.Series = Series;
    }


}
