/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 @author Admin
 */
@Entity
public class Passport extends Document
{

    @Basic
    private String series;

    @Basic
    private String issued_by;

    @Basic
    private String date_of_issue;

    @Basic
    private String registration;

    public String getSeries()
    {
        return this.series;
    }

    public void setSeries(String series)
    {
        this.series = series;
    }

    public String getIssued_by()
    {
        return this.issued_by;
    }

    public void setIssued_by(String issued_by)
    {
        this.issued_by = issued_by;
    }

    public String getDate_of_issue()
    {
        return this.date_of_issue;
    }

    public void setDate_of_issue(String date_of_issue)
    {
        this.date_of_issue = date_of_issue;
    }

    public String getRegistration()
    {
        return this.registration;
    }

    public void setRegistration(String registration)
    {
        this.registration = registration;
    }

}
