/**
 * This file was generated by the Jeddict
 */ 

package org.sibsutis.is.database.model.entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 * @author Admin
 */

@Entity
public class Professor extends Man implements Serializable { 

    @Basic
    private String Position;

    public String getPosition() {
        return this.Position;
    }

    public void setPosition(String Position) {
        this.Position = Position;
    }


}
