/**
 * This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.ElementCollection;
import javax.persistence.Embeddable;
import javax.persistence.Embedded;

/**
 * @author Eugene
 */
@Embeddable
public class Room
{

    @Basic
    private String NumberOfRoom;

    @Basic
    private String TypeOfRoom;

    @Basic
    private String RoomSize;

    @Basic
    private String TotalWindows;

    @Basic
    private String NumOfSubrooms;

    @Basic
    private String Line380v;

    @ElementCollection
    private List<String> ListFurniture;

    @ElementCollection
    private List<String> ListDevices;

    @Embedded
    private Communications communications;

    @Embedded
    private Furnitures furnitures;

    public String getNumberOfRoom()
    {
        return this.NumberOfRoom;
    }

    public void setNumberOfRoom(String NumberOfRoom)
    {
        this.NumberOfRoom = NumberOfRoom;
    }

    public String getTypeOfRoom()
    {
        return this.TypeOfRoom;
    }

    public void setTypeOfRoom(String TypeOfRoom)
    {
        this.TypeOfRoom = TypeOfRoom;
    }

    public String getRoomSize()
    {
        return this.RoomSize;
    }

    public void setRoomSize(String RoomSize)
    {
        this.RoomSize = RoomSize;
    }

    public String getTotalWindows()
    {
        return this.TotalWindows;
    }

    public void setTotalWindows(String TotalWindows)
    {
        this.TotalWindows = TotalWindows;
    }

    public String getNumOfSubrooms()
    {
        return this.NumOfSubrooms;
    }

    public void setNumOfSubrooms(String NumOfSubrooms)
    {
        this.NumOfSubrooms = NumOfSubrooms;
    }

    public String getLine380v()
    {
        return this.Line380v;
    }

    public void setLine380v(String Line380v)
    {
        this.Line380v = Line380v;
    }

    public List<String> getListFurniture()
    {
        return this.ListFurniture;
    }

    public void setListFurniture(List<String> ListFurniture)
    {
        this.ListFurniture = ListFurniture;
    }

    public List<String> getListDevices()
    {
        return this.ListDevices;
    }

    public void setListDevices(List<String> ListDevices)
    {
        this.ListDevices = ListDevices;
    }

    public Communications getCommunications()
    {
        return this.communications;
    }

    public void setCommunications(Communications communications)
    {
        this.communications = communications;
    }

    public Furnitures getFurnitures()
    {
        return this.furnitures;
    }

    public void setFurnitures(Furnitures furnitures)
    {
        this.furnitures = furnitures;
    }

}
