/**
 * This file was generated by the Jeddict
 */ 

package org.sibsutis.is.database.model.entity;

import java.io.Serializable;
import javax.persistence.Entity;

/**
 * @author Admin
 */

@Entity
public class Student extends Man implements Serializable { 

}
