/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 @author Admin
 */
@Entity
public class Education extends Document
{

    @Basic
    private String EducationDocument;

    @Basic
    private String DateOfIssue;

    @Basic
    private String LevelOfEducation;

    @Basic
    private String YearEnding;

    @Basic
    private String NameOfInstitution;

    public String getEducationDocument()
    {
        return this.EducationDocument;
    }

    public void setEducationDocument(String EducationDocument)
    {
        this.EducationDocument = EducationDocument;
    }

    public String getDateOfIssue()
    {
        return this.DateOfIssue;
    }

    public void setDateOfIssue(String DateOfIssue)
    {
        this.DateOfIssue = DateOfIssue;
    }

    public String getLevelOfEducation()
    {
        return this.LevelOfEducation;
    }

    public void setLevelOfEducation(String LevelOfEducation)
    {
        this.LevelOfEducation = LevelOfEducation;
    }

    public String getYearEnding()
    {
        return this.YearEnding;
    }

    public void setYearEnding(String YearEnding)
    {
        this.YearEnding = YearEnding;
    }

    public String getNameOfInstitution()
    {
        return this.NameOfInstitution;
    }

    public void setNameOfInstitution(String NameOfInstitution)
    {
        this.NameOfInstitution = NameOfInstitution;
    }

}
