/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;

/**
 @author Admin
 */
@Entity
public class Passport extends Document
{

    @Basic
    private String IssuedBy;

    @Basic
    private String DateOfIssue;

    @Basic
    private String Registration;

    public String getIssuedBy()
    {
        return this.IssuedBy;
    }

    public void setIssuedBy(String IssuedBy)
    {
        this.IssuedBy = IssuedBy;
    }

    public String getDateOfIssue()
    {
        return this.DateOfIssue;
    }

    public void setDateOfIssue(String DateOfIssue)
    {
        this.DateOfIssue = DateOfIssue;
    }

    public String getRegistration()
    {
        return this.Registration;
    }

    public void setRegistration(String Registration)
    {
        this.Registration = Registration;
    }

}
