/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Entity;

/**
 @author Admin
 */
@Entity
public class Policy extends Document
{

}
