/**
 * This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Entity;

/**
 * @author vaganovdv
 */
@Entity
public class Student extends Man {

}
