/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import java.util.List;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;

/**
 @author Maximus
 */
@Entity
public class UnifiedStateExam extends Document
{

    @ElementCollection
    private List<String> Discipline;

    @ElementCollection
    private List<String> Score;

    @ElementCollection
    private List<String> DeliveryDate;

    public List<String> getDiscipline()
    {
        return this.Discipline;
    }

    public void setDiscipline(List<String> Discipline)
    {
        this.Discipline = Discipline;
    }

    public List<String> getScore()
    {
        return this.Score;
    }

    public void setScore(List<String> Score)
    {
        this.Score = Score;
    }

    public List<String> getDeliveryDate()
    {
        return this.DeliveryDate;
    }

    public void setDeliveryDate(List<String> DeliveryDate)
    {
        this.DeliveryDate = DeliveryDate;
    }

}
