/**
 This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 Кафедра
 @author Maximus
 */
@Entity
public class Pulpit
{

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToMany(targetEntity = Professor.class)
    private List<Professor> professors;

    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public List<Professor> getProfessors()
    {
        return this.professors;
    }

    public void setProfessors(List<Professor> professors)
    {
        this.professors = professors;
    }

}
