/**
 * This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import javax.persistence.Basic;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * @author vaganovdv
 */
@MappedSuperclass
public abstract class Reports
{

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String Diploma_Project;

    @Basic
    private String Course_Project;

    @Basic
    private String Settlement_Project;

    @Basic
    private String Settlement_and_Graphic_Project;

    @Basic
    private String Practical_Work;

    @Basic
    private String Laboratory_Work;

    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public String getDiploma_Project()
    {
        return this.Diploma_Project;
    }

    public void setDiploma_Project(String Diploma_Project)
    {
        this.Diploma_Project = Diploma_Project;
    }

    public String getCourse_Project()
    {
        return this.Course_Project;
    }

    public void setCourse_Project(String Course_Project)
    {
        this.Course_Project = Course_Project;
    }

    public String getSettlement_Project()
    {
        return this.Settlement_Project;
    }

    public void setSettlement_Project(String Settlement_Project)
    {
        this.Settlement_Project = Settlement_Project;
    }

    public String getSettlement_and_Graphic_Project()
    {
        return this.Settlement_and_Graphic_Project;
    }

    public void setSettlement_and_Graphic_Project(String Settlement_and_Graphic_Project)
    {
        this.Settlement_and_Graphic_Project = Settlement_and_Graphic_Project;
    }

    public String getPractical_Work()
    {
        return this.Practical_Work;
    }

    public void setPractical_Work(String Practical_Work)
    {
        this.Practical_Work = Practical_Work;
    }

    public String getLaboratory_Work()
    {
        return this.Laboratory_Work;
    }

    public void setLaboratory_Work(String Laboratory_Work)
    {
        this.Laboratory_Work = Laboratory_Work;
    }

}
