/**
 * This file was generated by the Jeddict
 */
package org.sibsutis.is.database.model.entity;

import java.util.List;
import java.util.Map;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author Vadim
 */
@Entity
public class Student
{

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ElementCollection
    private Map<String, String> Personal_Information;

    @OneToMany(targetEntity = Information_of_Works.class)
    private List<Information_of_Works> information_of_Workses;

    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public Map<String, String> getPersonal_Information()
    {
        return this.Personal_Information;
    }

    public void setPersonal_Information(Map<String, String> Personal_Information)
    {
        this.Personal_Information = Personal_Information;
    }

    public List<Information_of_Works> getInformation_of_Workses()
    {
        return this.information_of_Workses;
    }

    public void setInformation_of_Workses(List<Information_of_Works> information_of_Workses)
    {
        this.information_of_Workses = information_of_Workses;
    }

}
